# permissions for end users to edit caminonodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: camino-editor-role
rules:
- apiGroups:
  - chain.camino.foundation
  resources:
  - caminonodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chain.camino.foundation
  resources:
  - caminonodes/status
  verbs:
  - get
