# permissions for end users to edit caminogoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caminogo-editor-role
rules:
- apiGroups:
  - chain.avax.network
  resources:
  - caminogoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chain.avax.network
  resources:
  - caminogoes/status
  verbs:
  - get
