# permissions for end users to view caminonodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: camino-viewer-role
rules:
- apiGroups:
  - chain.camino.foundation
  resources:
  - caminonodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chain.camino.foundation
  resources:
  - caminonodes/status
  verbs:
  - get
