# permissions for end users to view caminogoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caminogo-viewer-role
rules:
- apiGroups:
  - chain.avax.network
  resources:
  - caminogoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chain.avax.network
  resources:
  - caminogoes/status
  verbs:
  - get
