
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - chain.avax.network
  resources:
  - avalanchegoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chain.avax.network
  resources:
  - avalanchegoes/finalizers
  verbs:
  - update
- apiGroups:
  - chain.avax.network
  resources:
  - avalanchegoes/status
  verbs:
  - get
  - patch
  - update
