apiVersion: chain.camino.foundation/v1alpha1
kind: Camino
metadata:
  name: camino-test-worker
spec:
  deploymentName: test-worker
  bootstrapperURL: camino-test-validator-0-service
  nodeCount: 2
  image: c4tplatform/camino-node
  tag: v1.6.0
  env:
  - name: CAMINO_LOG_LEVEL
    value: debug
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
# Genesis is in deployed validator status
  genesis: ''
