apiVersion: chain.camino.foundation/v1alpha1
kind: Camino
metadata:
  name: camino-test-validator
spec:
  # Add fields here
  deploymentName: test-validator
  nodeCount: 5
  image: c4tplatform/camino-node
  tag: v1.7.3
  env:
  - name: CAMINO_LOG_LEVEL
    value: debug
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
  podLabels:
    test: test
  podAnnotations:
    test: test
  # Example when using pre-defined secrets
  # existingSecrets:
  # - custom-camino-test-validator-0-key
  # - custom-camino-test-validator-1-key
  # - custom-camino-test-validator-2-key
