apiVersion: chain.avax.network/v1alpha1
kind: Avalanchego
metadata:
  name: avalanchego-sample
spec:
  # Add fields here
  nodeKeys:
  - certificate: "testcert0"
    key: "testkey0"
  - certificate: "testcert1"
    key: "testkey1"
  - certificate: "testcert2"
    key: "testkey2"

